document.writeln("<div class=\'navbar navbar-default\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("        <div class=\'navbar-header \'>");
document.writeln("            <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\'");
document.writeln("                    data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("                <span class=\'icon-bar\'></span>");
document.writeln("            </button>");
document.writeln("            <a class=\'navbar-brand\' href=\'index.html\'>码教授</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("            <ul class=\'nav navbar-nav\'>");
document.writeln("                <li><a href=\'index.html\' class=\'dropdown-toggle\'>");
document.writeln("                    <span class=\'glyphicon glyphicon-home\' aria-hidden=\'true\'></span>");
document.writeln("                    后台首页<span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'user.html\' class=\'dropdown-toggle\'>");
document.writeln("                        <span class=\'glyphicon glyphicon-user\' aria-hidden=\'true\'></span>");
document.writeln("                        用户管理</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'cont.html\' class=\'dropdown-toggle\' >");
document.writeln("                        <span class=\'glyphicon glyphicon-list-alt\' aria-hidden=\'true\'></span>");
document.writeln("                        内容管理</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'Tabpage.html\' class=\'dropdown-toggle\'>");
document.writeln("                        <span class=\'glyphicon glyphicon-tag\' aria-hidden=\'true\'></span>");
document.writeln("                        标签管理</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <ul class=\'nav navbar-nav navbar-right visible-lg visible-md\'>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\'");
document.writeln("                       aria-expanded=\'false\'>admin <span class=\'caret\'></span></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'#\'>");
document.writeln("                            <span class=\'glyphicon glyphicon-screenshot\' aria-hidden=\'true\'></span>");
document.writeln("                            前台首页");
document.writeln("                        </a></li>");
document.writeln("                        <li><a href=\'#\'>");
document.writeln("                            <span class=\'glyphicon glyphicon-user\' aria-hidden=\'true\'></span>");
document.writeln("                            个人主页");
document.writeln("");
document.writeln("                        </a></li>");
document.writeln("                        <li><a href=\'#\'>");
document.writeln("                            <span class=\'glyphicon glyphicon-cog\' aria-hidden=\'true\'></span>");
document.writeln("                            个人设置");
document.writeln("                        </a></li>");
document.writeln("                        <li><a href=\'#\'>");
document.writeln("                            <span class=\'glyphicon glyphicon-credit-card\' aria-hidden=\'true\'></span>");
document.writeln("                            账户中心");
document.writeln("                        </a></li>");
document.writeln("                        <li><a href=\'#\'>");
document.writeln("                            <span class=\'glyphicon glyphicon-heart\' aria-hidden=\'true\'></span>");
document.writeln("                            我的收藏");
document.writeln("                        </a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li><a href=\'#\'>");
document.writeln("                    <span class=\'glyphicon glyphicon-off\' aria-hidden=\'true\'></span>");
document.writeln("                    退出");
document.writeln("                </a></li>");
document.writeln("                <li class=\'dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\'");
document.writeln("                       aria-expanded=\'false\'>");
document.writeln("                        关于微信");
document.writeln("                        <span class=\'caret\'></span>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");